### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-1-evaluacion-intermedia-albasmg#1]
Muy buen trabajo @albasmg!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 270 / 347
- [x] HTML > LINK: Debemos tener dos ficheros de estilos importados con un `link`.
- [x] HTML > LINK: El fichero de fuentes debe estar antes que nuestro fichero de estilos para que ningún fichero de estilos externo sobre escriba los nuestros.
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > HEADER: Necesitamos dos etiquetas `a` en el menu, dentro de los `li`.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Blog". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Contacto". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: Los enlaces tienen que tener el atributo `title`.
- [x] HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos. `.header-menu { font-size: 16px }`
- [x] CSS > FONT-SIZE: El tamaño del h1 en móvil debe ser 30px.
- [x] CSS > FONT-SIZE: El tamaño del h1 en tablet debe ser 40px.
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.
- [x] CSS > FLEX: El HEADER en tablet debe tener los elementos alineados a izquierda y derecha .

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te enjaca dímelo cuanto antes por favor.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by albasmg** [comment]
Hola @migueldelmazo!

Ya he subido el ejercicio con las mejoras. La única duda que tengo es sobre este punto: 
 CSS > FLEX: El HEADER en tablet debe tener los elementos alineados a izquierda y derecha
He alineado los dos elementos del header con un `justify-content: space-between`, ¿es que es mejor práctica alinear cada elemento por separado?
Gracias!! :)

**Comment by migueldelmazo** [comment]
Hola @albasmg 

> CSS > FLEX: El HEADER en tablet debe tener los elementos alineados a izquierda y derecha
He alineado los dos elementos del header con un justify-content: space-between, ¿es que es mejor práctica alinear cada elemento por separado?

Este tiene pinta de ser un fallo mío. Está bien como lo tienes. Muy buen curro, sigue así!!!
